version: 2
jobs:
  build:
    working_directory: ~/server
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test